apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hoon-blog-next-js.fullname" . }}
  labels:
    {{- include "hoon-blog-next-js.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hoon-blog-next-js.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hoon-blog-next-js.labels" . | nindent 8 }}
      annotations: 
        date: "{{ now }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
